// <auto-generated />
using System;
using IagoAuction.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IagoAuction.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190512101153_LotUpdate")]
    partial class LotUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("IagoAuction.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("IagoAuction.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BidderId");

                    b.Property<DateTime?>("Date");

                    b.Property<int?>("LotId");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BidderId");

                    b.HasIndex("LotId");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("IagoAuction.Models.Bidder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Bidder");
                });

            modelBuilder.Entity("IagoAuction.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AuctionId");

                    b.Property<int?>("PaintingId");

                    b.Property<int?>("paintingId");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("paintingId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("IagoAuction.Models.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<int?>("LotId");

                    b.Property<decimal?>("SuggestedStartPrice")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("Paintings");
                });

            modelBuilder.Entity("IagoAuction.Models.Bid", b =>
                {
                    b.HasOne("IagoAuction.Models.Bidder", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId");

                    b.HasOne("IagoAuction.Models.Lot", "Lot")
                        .WithMany("Bids")
                        .HasForeignKey("LotId");
                });

            modelBuilder.Entity("IagoAuction.Models.Lot", b =>
                {
                    b.HasOne("IagoAuction.Models.Auction", "Auction")
                        .WithMany("Lots")
                        .HasForeignKey("AuctionId");

                    b.HasOne("IagoAuction.Models.Painting", "Painting")
                        .WithMany()
                        .HasForeignKey("paintingId");
                });

            modelBuilder.Entity("IagoAuction.Models.Painting", b =>
                {
                    b.HasOne("IagoAuction.Models.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId");
                });
#pragma warning restore 612, 618
        }
    }
}
